#!/usr/bin/env python3
"""Render pgeu-system local_settings.py from runtime environment."""

from __future__ import annotations

import json
import os
import re
import secrets
import stat
from pathlib import Path

OAUTH_PROVIDER_RE = re.compile(r"^[a-z][a-z0-9_]*$")


def env(name: str, default: str = "") -> str:
    return os.environ.get(name, default)


def bool_env(name: str, default: bool = False) -> bool:
    raw = os.environ.get(name)
    if raw is None or raw == "":
        return default
    return raw.lower() in {"1", "true", "yes", "on"}


def list_env(name: str, default: str = "") -> list[str]:
    raw = env(name, default)
    return [item.strip() for item in raw.split(",") if item.strip()]


def secret_value(name: str, *, required: bool = True, allow_ephemeral: bool = False) -> str:
    file_name = f"{name}_FILE"
    direct_value = os.environ.get(name)
    file_value = os.environ.get(file_name)

    if file_value:
        path = Path(file_value)
        if not path.is_file():
            raise SystemExit(f"[pgeu-settings] missing secret file for {name}: {path}")
        return path.read_text(encoding="utf-8").strip()

    if direct_value:
        return direct_value

    if allow_ephemeral:
        return secrets.token_urlsafe(50)

    if required:
        raise SystemExit(f"[pgeu-settings] missing {name} or {file_name}")

    return ""


def py(value: object) -> str:
    return repr(value)


def oauth_provider_env_name(provider: str) -> str:
    return provider.upper()


def extra_oauth_providers() -> list[str]:
    raw = env("PGEU_EXTRA_OAUTH_PROVIDERS", env("PGEU_OAUTH_PROVIDERS", ""))
    providers: list[str] = []
    seen: set[str] = {"keycloak"}
    for provider in [item.lower() for item in list_env("PGEU_EXTRA_OAUTH_PROVIDERS", raw)]:
        if provider in seen:
            continue
        if not OAUTH_PROVIDER_RE.fullmatch(provider):
            raise SystemExit(f"[pgeu-settings] invalid OAuth provider name: {provider}")
        providers.append(provider)
        seen.add(provider)
    return providers


def oauth_provider_config(provider: str) -> dict[str, str]:
    prefix = f"PGEU_OAUTH_{oauth_provider_env_name(provider)}"
    client_id = env(f"{prefix}_CLIENT_ID")
    if not client_id:
        raise SystemExit(f"[pgeu-settings] missing {prefix}_CLIENT_ID")
    secret = secret_value(f"{prefix}_CLIENT_SECRET")
    config = {
        "clientid": client_id,
        "secret": secret,
    }
    base_url = env(f"{prefix}_BASE_URL").rstrip("/")
    if base_url:
        config["baseurl"] = base_url
    return config


def main() -> None:
    app_dir = Path(env("PGEU_APP_DIR", "/app"))
    settings_dir = app_dir / "postgresqleu"
    settings_file = Path(env("PGEU_LOCAL_SETTINGS_FILE", str(settings_dir / "local_settings.py")))

    if not (settings_dir / "settings.py").is_file():
        raise SystemExit(f"[pgeu-settings] missing upstream settings.py under {settings_dir}")

    django_secret = secret_value(
        "PGEU_DJANGO_SECRET_KEY",
        allow_ephemeral=bool_env("PGEU_ALLOW_EPHEMERAL_DJANGO_SECRET_KEY", False),
    )
    db_password = secret_value("PGEU_DB_PASSWORD")

    enable_oauth = bool_env("PGEU_ENABLE_OAUTH_AUTH", True)
    keycloak_base_url = env("PGEU_KEYCLOAK_BASE_URL").rstrip("/")
    keycloak_client_id = env("PGEU_KEYCLOAK_CLIENT_ID", "pgeu")
    keycloak_client_secret = ""
    if enable_oauth:
        if not keycloak_base_url:
            raise SystemExit("[pgeu-settings] PGEU_KEYCLOAK_BASE_URL is required when OAuth is enabled")
        if not keycloak_client_id:
            raise SystemExit("[pgeu-settings] PGEU_KEYCLOAK_CLIENT_ID is required when OAuth is enabled")
        keycloak_client_secret = secret_value("PGEU_KEYCLOAK_CLIENT_SECRET")

    allowed_hosts = list_env("PGEU_ALLOWED_HOSTS", env("PGEU_HOST", "pgeu.localhost"))
    if not allowed_hosts:
        allowed_hosts = ["localhost"]

    site_base = env("PGEU_SITE_BASE", f"https://{allowed_hosts[0]}").rstrip("/")
    csrf_trusted = list_env("PGEU_CSRF_TRUSTED_ORIGINS", site_base)
    email_password = secret_value("PGEU_EMAIL_HOST_PASSWORD", required=False)

    static_root = env("PGEU_STATIC_ROOT", "/var/lib/pgeu/staticfiles")
    static_url = env("PGEU_STATIC_URL", "/static/")
    media_root = env("PGEU_MEDIA_ROOT", "/var/lib/pgeu/media")
    skin_directory = env("PGEU_SYSTEM_SKIN_DIRECTORY", env("PGEU_SKIN_DIRECTORY", "")).rstrip("/")
    Path(static_root).mkdir(parents=True, exist_ok=True)
    Path(media_root).mkdir(parents=True, exist_ok=True)

    lines = [
        "# Generated by services/pgeu/render-local-settings.py.",
        "# Do not commit this file or paste its contents into docs.",
        "import os",
        "",
        f"DEBUG = {bool_env('PGEU_DJANGO_DEBUG', False)}",
        f"ENABLE_MEMBERSHIP = {bool_env('PGEU_ENABLE_MEMBERSHIP', True)}",
        f"ENABLE_ELECTIONS = {bool_env('PGEU_ENABLE_ELECTIONS', True)}",
        f"DISABLE_HTTPS_REDIRECTS = {bool_env('PGEU_DISABLE_HTTPS_REDIRECTS', False)}",
        f"ALLOWED_HOSTS = {py(allowed_hosts)}",
        f"CSRF_TRUSTED_ORIGINS = {py(csrf_trusted)}",
        f"SECRET_KEY = {py(django_secret)}",
        f"DEFAULT_FROM_EMAIL = {py(env('PGEU_DEFAULT_FROM_EMAIL', env('PGEU_SERVER_EMAIL', 'noreply@example.org')))}",
        f"DEFAULT_EMAIL = {py(env('PGEU_DEFAULT_EMAIL', env('PGEU_DEFAULT_FROM_EMAIL', env('PGEU_SERVER_EMAIL', 'noreply@example.org'))))}",
        f"SERVER_EMAIL = {py(env('PGEU_SERVER_EMAIL', 'noreply@example.org'))}",
        f"EMAIL_BACKEND = {py(env('PGEU_EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend'))}",
        f"EMAIL_HOST = {py(env('PGEU_EMAIL_HOST', 'localhost'))}",
        f"EMAIL_PORT = {int(env('PGEU_EMAIL_PORT', '25'))}",
        f"EMAIL_HOST_USER = {py(env('PGEU_EMAIL_HOST_USER', ''))}",
        f"EMAIL_HOST_PASSWORD = {py(email_password)}",
        f"EMAIL_USE_TLS = {bool_env('PGEU_EMAIL_USE_TLS', False)}",
        f"EMAIL_USE_SSL = {bool_env('PGEU_EMAIL_USE_SSL', False)}",
        f"EMAIL_TIMEOUT = {int(env('PGEU_EMAIL_TIMEOUT', '10'))}",
        f"SITEBASE = {py(site_base)}",
        f"TIME_ZONE = {py(env('PGEU_TIME_ZONE', 'Europe/Paris'))}",
        f"SESSION_COOKIE_SECURE = {bool_env('PGEU_SESSION_COOKIE_SECURE', True)}",
        f"CSRF_COOKIE_SECURE = {bool_env('PGEU_CSRF_COOKIE_SECURE', True)}",
        'SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")',
        "USE_X_FORWARDED_HOST = True",
        f"STATIC_ROOT = {py(static_root)}",
        f"STATIC_URL = {py(static_url)}",
        f"MEDIA_ROOT = {py(media_root)}",
        f"MEDIA_URL = {py(env('PGEU_MEDIA_URL', '/media/'))}",
        "",
        "DATABASES = {",
        '    "default": {',
        '        "ENGINE": "django.db.backends.postgresql_psycopg2",',
        f'        "NAME": {py(env("PGEU_DB_NAME", "pgeu"))},',
        f'        "HOST": {py(env("PGEU_DB_HOST", "pgeu-db"))},',
        f'        "PORT": {py(env("PGEU_DB_PORT", "5432"))},',
        f'        "USER": {py(env("PGEU_DB_USER", "pgeu"))},',
        f'        "PASSWORD": {py(db_password)},',
        "    }",
        "}",
        "",
    ]

    if skin_directory:
        lines.extend(
            [
                f"SYSTEM_SKIN_DIRECTORY = {py(skin_directory)}",
                "STATICFILES_DIRS = (",
                '    ("local", os.path.join(SYSTEM_SKIN_DIRECTORY, "media")),',
                '    "media/",',
                ")",
                "",
            ]
        )

    if enable_oauth:
        oauth = {
            "keycloak": {
                "clientid": keycloak_client_id,
                "secret": keycloak_client_secret,
                "baseurl": keycloak_base_url,
            }
        }
        for provider in extra_oauth_providers():
            oauth[provider] = oauth_provider_config(provider)
        lines.extend(
            [
                "ENABLE_OAUTH_AUTH = True",
                f"OAUTH = {json.dumps(oauth, indent=4, sort_keys=True)}",
                "",
            ]
        )

    settings_file.parent.mkdir(parents=True, exist_ok=True)
    settings_file.write_text("\n".join(lines), encoding="utf-8")
    settings_file.chmod(stat.S_IRUSR | stat.S_IWUSR)
    print(f"[pgeu-settings] wrote {settings_file}")


if __name__ == "__main__":
    main()
